// <auto-generated />
using System;
using AiJobMarketIntelligence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiJobMarketIntelligence.Infrastructure.Migrations.JobsProcessed
{
    [DbContext(typeof(AiJobContext))]
    [Migration("20260611102502_AddJobApplications")]
    partial class AddJobApplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("JobRawId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("JobRawId");

                    b.HasIndex("UserId", "JobRawId")
                        .IsUnique()
                        .HasDatabaseName("IX_JobApplications_UserId_JobRawId_Unique");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobProcessed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("JobRawId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("SalaryMax")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryMin")
                        .HasColumnType("int");

                    b.Property<int>("SalaryPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("JobRawId")
                        .IsUnique();

                    b.ToTable("JobsProcessed");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SalaryRaw")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("IX_JobsRaw_Url_Unique")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 191 });

                    b.ToTable("JobsRaw");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobSkill", b =>
                {
                    b.Property<int>("JobRawId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("JobRawId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills", null, t =>
                        {
                            t.HasCheckConstraint("CK_JobSkill_Ids", "JobRawId > 0 AND SkillId > 0");
                        });
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Skills_Name_Unique");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.UserPreferences.UserJobPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PreferredJobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("PreferredSalaryMax")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredSalaryMin")
                        .HasColumnType("int");

                    b.Property<string>("SkillsText")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("WorkMode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserJobPreferences_UserId_Unique");

                    b.ToTable("UserJobPreferences");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("AiJobMarketIntelligence.Domain.Entities.JobRaw", "JobRaw")
                        .WithMany()
                        .HasForeignKey("JobRawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRaw");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobProcessed", b =>
                {
                    b.HasOne("AiJobMarketIntelligence.Domain.Entities.JobRaw", "JobRaw")
                        .WithOne("JobProcessed")
                        .HasForeignKey("AiJobMarketIntelligence.Domain.Entities.JobProcessed", "JobRawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRaw");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("AiJobMarketIntelligence.Domain.Entities.JobRaw", "JobRaw")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobRawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiJobMarketIntelligence.Domain.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRaw");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobRaw", b =>
                {
                    b.Navigation("JobProcessed");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.Skill", b =>
                {
                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
