// <auto-generated />
using System;
using AiJobMarketIntelligence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiJobMarketIntelligence.Infrastructure.Migrations
{
    [DbContext(typeof(AiJobContext))]
    partial class AiJobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobProcessed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRawId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaryMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaryMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobRawId")
                        .IsUnique();

                    b.ToTable("JobsProcessed");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryRaw")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("IX_JobsRaw_Url_Unique");

                    b.ToTable("JobsRaw");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobSkill", b =>
                {
                    b.Property<int>("JobRawId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobRawId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills", null, t =>
                        {
                            t.HasCheckConstraint("CK_JobSkill_Ids", "[JobRawId] > 0 AND [SkillId] > 0");
                        });
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Skills_Name_Unique");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobProcessed", b =>
                {
                    b.HasOne("AiJobMarketIntelligence.Domain.Entities.JobRaw", "JobRaw")
                        .WithOne("JobProcessed")
                        .HasForeignKey("AiJobMarketIntelligence.Domain.Entities.JobProcessed", "JobRawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRaw");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("AiJobMarketIntelligence.Domain.Entities.JobRaw", "JobRaw")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobRawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiJobMarketIntelligence.Domain.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRaw");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.JobRaw", b =>
                {
                    b.Navigation("JobProcessed");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("AiJobMarketIntelligence.Domain.Entities.Skill", b =>
                {
                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
